
language: groovy
cache:
  directories:
  - $HOME/.gradle
  - node_modules

install:
  - npm install elm

before_script:
  - find . -iname "elm-make"
  - ls -al "node_modules/.bin"
  - export ELM_EXECUTABLE="node_modules/.bin/elm-make"
  - $ELM_EXECUTABLE -y

script:
  - ./gradlew assemble
  - ./gradlew check -i
