
language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules

env:
  - NODE_VERSION=4.0
  - ELM_VERSION=0.18.0

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm-use elm-test
  - elm-use $ELM_VERSION
  - chmod +x $(npm config get prefix)/bin/elm-make

before_script:
  - pwd
  - elm-make --yes

script:
  - ./gradlew assemble
  - ./gradlew check -i
