
language: groovy
cache:
  directories:
  - $HOME/.gradle
  - node_modules

install:
  - npm install elm

before_script:
  - find . -iname "elm-make"
  - ls -al ~/node_modules/.bin
  - ls -al $HOME/node_modules/.bin
  - export ELM_EXECUTABLE=$HOME/node_modules/.bin/elm-make
  - $ELM_EXECUTABLE

script:
  - ./gradlew assemble
  - ./gradlew check -i
