
language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules
    - sysconfcpus

env:
  - NODE_VERSION=4.0 ELM_VERSION=0.19.0

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm-use
  - elm-use $ELM_VERSION
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-original
  - printf "#\041/bin/bash\n\necho \"Running elm with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-original \"\$@\"" > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm

script:
  - ./gradlew assemble
  - ./gradlew check -i
